@host = http://localhost:8080/higia-server/api

###
# @name Register
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "string",
  "Name": "user",
  "IsAdmin": true,
  "Number": "000000000000"
}

###
# @name Login
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "string"
}